#!/usr/bin/env ruby
# coding: utf-8
# %filename%
# created on %date%
# (c) %year% %author%
# Time-stamp: <2025-03-17 23:17:10 krylon>

require 'rubygems'

=begin rdoc
%module%
Purpose:
Dependencies:
=end

